### PR TITLE
travis-ci, cmake and appveyer support added

### PR DESCRIPTION
**Pull request by holgern**

### CODE REVIEW

**Comment by holgern** [comment]
Ok, it works finally:
https://travis-ci.org/holgern/wavelib
https://ci.appveyor.com/project/HolgerNahrstaedt/wavelib

**Comment by rafat** [comment]
cmake is failing on Ubuntu (Boost 1.54) with the following error

`cmake -G "Unix Makefiles"
>>> Building Wavelib version: 1.0.0
>>> EXECUTABLE_OUTPUT_PATH = /home/rafat/code/waveunit/Bin/
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Linking against boost dynamic libraries
CMake Error: An attempt was made to access a variable: BOOST_DIR that has not been defined.
`

I guess CmakeLists.txt is executing "include_directories(${BOOST_DIR})" and it has not been defined in any of the configuration files.

**Comment by holgern** [comment]
Ok, i removed this line

**Comment by rafat** [comment]
Yeah, it is now working on Ubuntu. Let me run the test on Cygwin.

**Comment by rafat** [comment]
Cygwin with Boost 1.58 test also successful.

**Pull request merged**
