### PR TITLE
Const-correctness, unused parameter cleanup, build system improvements

### PR DESCRIPTION
**Pull request by aitap**
Hi!

Originally I intended to just drop a few `const`s before pointer arguments in functions that don't change the arguments to make the code easier to optimize (also, to allow passing string literals in C++, where those are `const char *` and produce warnings otherwise), but ended up changing more:

* Build system: make it possible to build the tests in MSVC2010:
   * Don't link to `m` library unless building for UNIX
   * Fix the only instance of executable statements being before variable declarations, in `factorial` in `cwt.c`, since MSVC2010 is a C89
* A lot of unused function parameters, static functions and set but unused variables are cleaned up
* A few cases of different headers defining same things with redundancy are cleaned up
* Finally, the public interface functions are mostly const-correct

My changes don't seem to break the tests on Linux/gcc6.3.0 or Windows/MSVC2010.

Are you interested in any of that?

### CODE REVIEW

**Comment by rafat** [comment]
Hi,

These changes look good but there are a couple of minor issues.

1. tst_dwt.cpp is throwing a printf error and you may want to include
<cstdio> to deal with that.

2. In cwt.h and cwt.c , s0 and dj are needed for reconstruction. They
are unused variables in this implementation because I have used
default values for the three wavelets. Both of these variables may be
needed if we are to add more wavelets. I think it might be a good idea
to let them be for this time.

Can you fix these two things so I can merge your branch with the main ?

Rafat

**Comment by aitap** [comment]
Thank you for the quick reply!

On Fri, 14 Dec 2018 09:18:54 +0000 (UTC)
Rafat Hussain <notifications@github.com> wrote:

> 1. tst_dwt.cpp is throwing a printf error and you may want to include
> <cstdio> to deal with that.

Fixed. I wonder why it didn't crash for me, despite not having the
header included.
 
> 2. In cwt.h and cwt.c , s0 and dj are needed for reconstruction. <...>
> Both of these variables may be needed if we are to add more wavelets.

Also fixed, thanks for the explanation.

While tending to the issues, I found some more unused parameters,
variables and redundant typedefs and removed them. To make sure I
didn't miss anything else, I reconfigured the project with
`-DCMAKE_C_FLAGS='-Wall -Wextra --std=gnu89 -fsanitize=address
-fsanitize=undefined' -DCMAKE_CXX_FLAGS='-Wall -Wextra --std=gnu++11
-fsanitize=address -fsanitize=undefined'
-DCMAKE_EXE_LINKER_LAGS='-fsanitize=address -fsanitize=undefined'` and
ran `make clean all test`. No new warnings or errors showed up.

-- 
Best regards,
Ivan

**Comment by rafat** [comment]
Hi Ivan,

 Thanks for cleaning up the code. I have merged your branch with the
main branch.You may want to pull the main branch and check if
everything is working as it should.

Rafat

**Comment by aitap** [comment]
Hi Rafat,

On Fri, 14 Dec 2018 03:15:41 -0800
Rafat Hussain <notifications@github.com> wrote:

> You may want to pull the main branch and check if
> everything is working as it should.

My code that uses your library to find peaks in noisy signal hasn't
suffered any regressions, either.

Thanks for your work!

-- 
Best regards,
Ivan

**Pull request merged**
